### ISSUE TITLE
NameError: name 'raw_input' is not defined

### ISSUE THREAD

**Issue by SidepocketNeo** [noobscode/kalel#2]
My output when I try to run setup.py:

Setting up KalEl For You...
Traceback (most recent call last):
  File "setup.py", line 232, in <module>
    install()
  File "setup.py", line 29, in install
    reinstall = raw_input('KalEl is allready installed!\nDo you want to uninstall? (y/n): ')
NameError: name 'raw_input' is not defined

**Comment by noobscode** [comment]
What version of python where you using?
